# Importing all the required libraties

In [81]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Loading, Pre-Processing data

In [82]:
df = pd.read_csv('full_german_credit.csv')
df.head()

,Status_of_existing_checking_account,Duration_in_month,Credit_history,Purpose,Credit_amount,Savings_account_bonds,Present_employment_since,Installment_rate_in_percentage_of_disposable_income,Personal_status_and_sex,Other_debtors_guarantors,...,Property,Age_in_years,Other_installment_plans,Housing,Number_of_existing_credits_at_this_bank,Job,Number_of_people_being_liable_to_provide_maintenance_for,Telephone,Foreign_worker,Risk
0,< 0 DM,6,critical account / other credits existing (not...,radio/TV,1169,/ no savings,>= 7 years,4,male: single,NaN,...,real estate,67,NaN,own,2,skilled employee / official,1,"yes, registered under the customers name",yes,good
1,0 <= ... < 200 DM,48,existing credits paid back duly till now,radio/TV,5951,< 100 DM,1 <= ... < 4 years,2,female: divorced/separated/married,NaN,...,real estate,22,NaN,own,1,skilled employee / official,1,NaN,yes,bad
2,no checking account,12,critical account / other credits existing (not...,education,2096,< 100 DM,4 <= ... < 7 years,2,male: single,NaN,...,real estate,49,NaN,own,1,unskilled - resident,2,NaN,yes,good
3,< 0 DM,42,existing credits paid back duly till now,furniture/equipment,7882,< 100 DM,4 <= ... < 7 years,2,male: single,guarantor,...,building society savings agreement / life insu...,45,NaN,for free,1,skilled employee / official,2,NaN,yes,good
4,< 0 DM,24,delay in paying off in the past,car (new),4870,< 100 DM,1 <= ... < 4 years,3,male: single,NaN,...,/ no property,53,NaN,for free,2,skilled employee / official,2,NaN,yes,bad

In [83]:
print(df.info())
print(df.nunique())
print(df.notnull())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   Status_of_existing_checking_account                       1000 non-null   object
 1   Duration_in_month                                         1000 non-null   int64
 2   Credit_history                                            1000 non-null   object
 3   Purpose                                                   1000 non-null   object
 4   Credit_amount                                             1000 non-null   int64
 5   Savings_account_bonds                                     1000 non-null   object
 6   Present_employment_since                                  1000 non-null   object
 7   Installment_rate_in_percentage_of_disposable_income       1000 non-null   int64
 8   Personal_status_and_sex                                   1000 non-null   object
 9   Other_debtors_guarantors                                  93 non-null     object
 10  Present_residence_since                                   1000 non-null   int64
 11  Property                                                  1000 non-null   object
 12  Age_in_years                                              1000 non-null   int64
 13  Other_installment_plans                                   186 non-null    object
 14  Housing                                                   1000 non-null   object
 15  Number_of_existing_credits_at_this_bank                   1000 non-null   int64
 16  Job                                                       1000 non-null   object
 17  Number_of_people_being_liable_to_provide_maintenance_for  1000 non-null   int64
 18  Telephone                                                 404 non-null    object
 19  Foreign_worker                                            1000 non-null   object
 20  Risk                                                      1000 non-null   object
dtypes: int64(7), object(14)
memory usage: 164.2+ KB
None
Status_of_existing_checking_account                           4
Duration_in_month                                            33
Credit_history                                                5
Purpose                                                      10
Credit_amount                                               921
Savings_account_bonds                                         5
Present_employment_since                                      5
Installment_rate_in_percentage_of_disposable_income           4
Personal_status_and_sex                                       4
Other_debtors_guarantors                                      2
Present_residence_since                                       4
Property                                                      4
Age_in_years                                                 53
Other_installment_plans                                       2
Housing                                                       3
Number_of_existing_credits_at_this_bank                       4
Job                                                           4
Number_of_people_being_liable_to_provide_maintenance_for      2
Telephone                                                     1
Foreign_worker                                                2
Risk                                                          2
dtype: int64
     Status_of_existing_checking_account  Duration_in_month  Credit_history  \
0                                   True               True            True
1                                   True               True            True
2                                   True               True            True
3                                   True               True            True
4                                   True               True            True
..                                   ...                ...             ...
995                                 True               True            True
996                                 True               True            True
997                                 True               True            True
998                                 True               True            True
999                                 True               True            True

     Purpose  Credit_amount  Savings_account_bonds  Present_employment_since  \
0       True           True                   True                      True
1       True           True                   True                      True
2       True           True                   True                      True
3       True           True                   True                      True
4       True           True                   True                      True
..       ...            ...                    ...                       ...
995     True           True                   True                      True
996     True           True                   True                      True
997     True           True                   True                      True
998     True           True                   True                      True
999     True           True                   True                      True

     Installment_rate_in_percentage_of_disposable_income  \
0                                                 True
1                                                 True
2                                                 True
3                                                 True
4                                                 True
..                                                 ...
995                                               True
996                                               True
997                                               True
998                                               True
999                                               True

     Personal_status_and_sex  Other_debtors_guarantors  ...  Property  \
0                       True                     False  ...      True
1                       True                     False  ...      True
2                       True                     False  ...      True
3                       True                      True  ...      True
4                       True                     False  ...      True
..                       ...                       ...  ...       ...
995                     True                     False  ...      True
996                     True                     False  ...      True
997                     True                     False  ...      True
998                     True                     False  ...      True
999                     True                     False  ...      True

     Age_in_years  Other_installment_plans  Housing  \
0            True                    False     True
1            True                    False     True
2            True                    False     True
3            True                    False     True
4            True                    False     True
..            ...                      ...      ...
995          True                    False     True
996          True                    False     True
997          True                    False     True
998          True                    False     True
999          True                    False     True

     Number_of_existing_credits_at_this_bank   Job  \
0                                       True  True
1                                       True  True
2                                       True  True
3                                       True  True
4                                       True  True
..                                       ...   ...
995                                     True  True
996                                     True  True
997                                     True  True
998                                     True  True
999                                     True  True

     Number_of_people_being_liable_to_provide_maintenance_for  Telephone  \
0                                                 True              True
1                                                 True             False
2                                                 True             False
3                                                 True             False
4                                                 True             False
..                                                 ...               ...
995                                               True             False
996                                               True              True
997                                               True             False
998                                               True              True
999                                               True             False

     Foreign_worker  Risk
0              True  True
1              True  True
2              True  True
3              True  True
4              True  True
..              ...   ...
995            True  True
996            True  True
997            True  True
998            True  True
999            True  True

[1000 rows x 21 columns]
       Duration_in_month  Credit_amount  \
count        1000.000000    1000.000000
mean           20.903000    3271.258000
std            12.058814    2822.736876
min             4.000000     250.000000
25%            12.000000    1365.500000
50%            18.000000    2319.500000
75%            24.000000    3972.250000
max            72.000000   18424.000000

       Installment_rate_in_percentage_of_disposable_income  \
count                                        1000.000000
mean                                            2.973000
std                                             1.118715
min                                             1.000000
25%                                             2.000000
50%                                             3.000000
75%                                             4.000000
max                                             4.000000

       Present_residence_since  Age_in_years  \
count              1000.000000   1000.000000
mean                  2.845000     35.546000
std                   1.103718     11.375469
min                   1.000000     19.000000
25%                   2.000000     27.000000
50%                   3.000000     33.000000
75%                   4.000000     42.000000
max                   4.000000     75.000000

       Number_of_existing_credits_at_this_bank  \
count                              1000.000000
mean                                  1.407000
std                                   0.577654
min                                   1.000000
25%                                   1.000000
50%                                   1.000000
75%                                   2.000000
max                                   4.000000

       Number_of_people_being_liable_to_provide_maintenance_for
count                                        1000.000000
mean                                            1.155000
std                                             0.362086
min                                             1.000000
25%                                             1.000000
50%                                             1.000000
75%                                             1.000000
max                                             2.000000

In [84]:
df['Telephone'].fillna('unknown', inplace=True)
df['Other_installment_plans'].fillna('unknown', inplace=True)
df['Other_debtors_guarantors'].fillna('unknown', inplace=True)

column = df.columns

le = LabelEncoder()

print((df[column[1]].dtypes))

for cols in column:
    if df[cols].dtypes == "object":
        print("entered")
        df['encoded'+cols] = le.fit_transform(df[cols])

int64
entered
entered
entered
entered
entered
entered
entered
entered
entered
entered
entered
entered
entered
entered

C:\Users\Aarya Bhave\AppData\Local\Temp\ipykernel_28024\859361229.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Telephone'].fillna('unknown', inplace=True)
C:\Users\Aarya Bhave\AppData\Local\Temp\ipykernel_28024\859361229.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Other_installment_plans'].fillna('unknown', inplace=True)
C:\Users\Aarya Bhave\AppData\Local\Temp\ipykernel_28024\859361229.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Other_debtors_guarantors'].fillna('unknown', inplace=True)

In [85]:
df.head(2)

,Status_of_existing_checking_account,Duration_in_month,Credit_history,Purpose,Credit_amount,Savings_account_bonds,Present_employment_since,Installment_rate_in_percentage_of_disposable_income,Personal_status_and_sex,Other_debtors_guarantors,...,encodedPresent_employment_since,encodedPersonal_status_and_sex,encodedOther_debtors_guarantors,encodedProperty,encodedOther_installment_plans,encodedHousing,encodedJob,encodedTelephone,encodedForeign_worker,encodedRisk
0,< 0 DM,6,critical account / other credits existing (not...,radio/TV,1169,/ no savings,>= 7 years,4,male: single,unknown,...,3,3,2,3,2,1,1,1,1,1
1,0 <= ... < 200 DM,48,existing credits paid back duly till now,radio/TV,5951,< 100 DM,1 <= ... < 4 years,2,female: divorced/separated/married,unknown,...,0,0,2,3,2,1,1,0,1,0

In [86]:
for cols in column:
    if df[cols].dtypes == "object":
        df.drop([cols], axis=1, inplace=True)

# Defining the independent, dependent variables

In [87]:
X = df.drop(['encodedRisk'], axis=1)
y = df['encodedRisk']

# Applying train-test-split

In [88]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=3, shuffle=True, test_size=0.2)

# Building the network

In [89]:
model = Sequential()

model.add(Dense(16, input_dim = X_train.shape[1], activation = 'relu'))
model.add(Dense(10, activation = 'relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

c:\Users\Aarya Bhave\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

# Training the model

In [90]:
train = model.fit(X_train, y_train, epochs=50, batch_size=16, validation_split=0.2)

Epoch 1/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.2719 - loss: 383.7868 - val_accuracy: 0.4062 - val_loss: 230.5399
Epoch 2/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.2719 - loss: 224.9819 - val_accuracy: 0.4062 - val_loss: 118.9230
Epoch 3/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.2750 - loss: 87.9720 - val_accuracy: 0.4750 - val_loss: 8.3698
Epoch 4/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6750 - loss: 5.1078 - val_accuracy: 0.5938 - val_loss: 1.9101
Epoch 5/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7141 - loss: 0.9841 - val_accuracy: 0.6500 - val_loss: 0.9703
Epoch 6/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7234 - loss: 0.8367 - val_accuracy: 0.6375 - val_loss: 0.9075
Epoch 7/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7078 - loss: 0.7632 - val_accuracy: 0.6750 - val_loss: 0.8292
Epoch 8/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7250 - loss: 0.7265 - val_accuracy: 0.6812 - val_loss: 0.7984
Epoch 9/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7031 - loss: 0.7797 - val_accuracy: 0.6375 - val_loss: 0.7709
Epoch 10/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6844 - loss: 0.9051 - val_accuracy: 0.6375 - val_loss: 0.6987
Epoch 11/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6828 - loss: 0.9216 - val_accuracy: 0.6875 - val_loss: 0.7729
Epoch 12/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6438 - loss: 1.2396 - val_accuracy: 0.6438 - val_loss: 0.9115
Epoch 13/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6734 - loss: 0.9015 - val_accuracy: 0.6250 - val_loss: 0.9643
Epoch 14/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6656 - loss: 0.8784 - val_accuracy: 0.6375 - val_loss: 0.6744
Epoch 15/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6922 - loss: 0.6894 - val_accuracy: 0.6875 - val_loss: 0.6918
Epoch 16/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7000 - loss: 0.6861 - val_accuracy: 0.6250 - val_loss: 0.6999
Epoch 17/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7172 - loss: 0.6257 - val_accuracy: 0.6250 - val_loss: 0.7018
Epoch 18/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6969 - loss: 0.7205 - val_accuracy: 0.6250 - val_loss: 0.7984
Epoch 19/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7297 - loss: 0.6399 - val_accuracy: 0.6875 - val_loss: 0.6195
Epoch 20/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7000 - loss: 0.7776 - val_accuracy: 0.6250 - val_loss: 0.7891
Epoch 21/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7063 - loss: 0.7203 - val_accuracy: 0.6000 - val_loss: 1.1116
Epoch 22/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6625 - loss: 0.8532 - val_accuracy: 0.6125 - val_loss: 0.7851
Epoch 23/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7047 - loss: 0.6603 - val_accuracy: 0.5938 - val_loss: 1.1966
Epoch 24/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6562 - loss: 1.1066 - val_accuracy: 0.5938 - val_loss: 1.9737
Epoch 25/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6578 - loss: 1.0055 - val_accuracy: 0.6313 - val_loss: 0.9207
Epoch 26/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6828 - loss: 0.7759 - val_accuracy: 0.6938 - val_loss: 0.6451
Epoch 27/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7047 - loss: 0.6550 - val_accuracy: 0.6875 - val_loss: 0.6159
Epoch 28/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7063 - loss: 0.6805 - val_accuracy: 0.6438 - val_loss: 0.6575
Epoch 29/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6969 - loss: 0.7579 - val_accuracy: 0.6812 - val_loss: 0.5983
Epoch 30/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7156 - loss: 0.6305 - val_accuracy: 0.6125 - val_loss: 0.8120
Epoch 31/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6906 - loss: 0.6660 - val_accuracy: 0.6125 - val_loss: 0.7594
Epoch 32/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6625 - loss: 1.0204 - val_accuracy: 0.5938 - val_loss: 1.1379
Epoch 33/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6891 - loss: 0.7723 - val_accuracy: 0.6125 - val_loss: 0.7275
Epoch 34/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6656 - loss: 0.8294 - val_accuracy: 0.6562 - val_loss: 0.5908
Epoch 35/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6984 - loss: 0.6327 - val_accuracy: 0.5938 - val_loss: 1.2430
Epoch 36/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7156 - loss: 0.6597 - val_accuracy: 0.6125 - val_loss: 0.8160
Epoch 37/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6906 - loss: 0.8639 - val_accuracy: 0.5938 - val_loss: 1.4543
Epoch 38/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6875 - loss: 0.7665 - val_accuracy: 0.6062 - val_loss: 0.9388
Epoch 39/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7359 - loss: 0.5602 - val_accuracy: 0.6500 - val_loss: 0.5800
Epoch 40/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6984 - loss: 0.6070 - val_accuracy: 0.6625 - val_loss: 0.6224
Epoch 41/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7266 - loss: 0.5862 - val_accuracy: 0.6938 - val_loss: 0.5795
Epoch 42/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6781 - loss: 0.6920 - val_accuracy: 0.6062 - val_loss: 0.8476
Epoch 43/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6938 - loss: 0.8156 - val_accuracy: 0.6000 - val_loss: 1.0693
Epoch 44/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6641 - loss: 1.0161 - val_accuracy: 0.6062 - val_loss: 0.8509
Epoch 45/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7156 - loss: 0.6903 - val_accuracy: 0.6375 - val_loss: 0.6623
Epoch 46/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7203 - loss: 0.6277 - val_accuracy: 0.6062 - val_loss: 0.8209
Epoch 47/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7250 - loss: 0.6394 - val_accuracy: 0.7063 - val_loss: 0.5936
Epoch 48/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6687 - loss: 0.9359 - val_accuracy: 0.6000 - val_loss: 0.8756
Epoch 49/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7141 - loss: 0.6104 - val_accuracy: 0.6062 - val_loss: 0.8371
Epoch 50/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7156 - loss: 0.6539 - val_accuracy: 0.6187 - val_loss: 0.6778

# Calculating the accuracy

In [91]:
loss, accuracy = model.evaluate(X_test, y_test)
y_predict = model.predict(X_test)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6900 - loss: 0.6335
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step

In [93]:
print("Accuracy : ",accuracy)

Accuracy :  0.6899999976158142